### ISSUE TITLE
Move parsing optimization from ChannelDataArrayBlock to Channel

### ISSUE THREAD

**Issue by StokesMIDE** [MideTechnology/idelib#1]
The optimizations that create Numpy types appear to be done for every `ChannelDataArrayBlock`. These aren't really specific to a particular data block, and should probably be done once and cached in the parent `Channel` or its parser object.

**Comment by CFlaniganMide** [comment]
To clarify how this is being implemented:

the changes in #49 added `EventArray._npType`, which defines a numpy compatible type for the EventArray's data.  This is also compatible with the `minMeanMax` data, so the implementation in #66 uses that datatype to generate `minMeanMax` values instead of the parser.
