### ISSUE TITLE
parser fails on pressure channel in Travis tests

### ISSUE THREAD

**Issue by CrepeGoat** [MideTechnology/idelib#16]
see https://travis-ci.com/github/MideTechnology/ide_processing_scripts/jobs/389950857#L356

(Caused by https://github.com/MideTechnology/idelib-archive/pull/11?)

**Comment by StokesMIDE** [comment]
There are some other issues with the conversion of `struct` format strings to Numpy `dtype`; there does not appear to be a pad character, and unsigned 32b ints use a different character. You'll probably need something like a little lookup table, rather than use the characters in the format string verbatim.
